#!/usr/bin/env python3
import argparse
import http.client
import json
import os
import socket
import subprocess
import sys

try:
    import mercury
except ImportError:
    print("You must have python3-mercury installed for this script to work.")
    sys.exit(1)


# Whitelist of keys we either need to check or allow setting in APOLLO. The latter
# is strictly only true for 'mercury.aa_profile'.
keys_to_check = [
    'mercury.pts',
    # 'mercury.tty',
    # 'mercury.devttydir',
    # 'mercury.kmsg',
    'mercury.aa_profile',
    # 'mercury.cgroup.',
    'mercury.loglevel',
    # 'mercury.logfile',
    'mercury.mount.auto',
    'mercury.mount',
    # 'mercury.rootfs.mount',
    # 'mercury.rootfs.options',
    # 'mercury.pivotdir',
    # 'mercury.hook.pre-start',
    # 'mercury.hook.pre-mount',
    # 'mercury.hook.mount',
    # 'mercury.hook.autodev',
    # 'mercury.hook.start',
    # 'mercury.hook.stop',
    # 'mercury.hook.post-stop',
    # 'mercury.hook.clone',
    # 'mercury.hook.destroy',
    # 'mercury.hook',
    'mercury.network.type',
    'mercury.network.flags',
    'mercury.network.link',
    'mercury.network.name',
    'mercury.network.macvlan.mode',
    'mercury.network.veth.pair',
    # 'mercury.network.script.up',
    # 'mercury.network.script.down',
    'mercury.network.hwaddr',
    'mercury.network.mtu',
    # 'mercury.network.vlan.id',
    # 'mercury.network.ipv4.gateway',
    # 'mercury.network.ipv4',
    # 'mercury.network.ipv6.gateway',
    # 'mercury.network.ipv6',
    # 'mercury.network.',
    # 'mercury.network',
    # 'mercury.console.logfile',
    # 'mercury.console',
    'mercury.include',
    'mercury.start.auto',
    'mercury.start.delay',
    'mercury.start.order',
    # 'mercury.monitor.unshare',
    # 'mercury.group',
    'mercury.environment',
    # 'mercury.init_cmd',
    # 'mercury.init_uid',
    # 'mercury.init_gid',
    # 'mercury.ephemeral',
    # 'mercury.syslog',
    # 'mercury.no_new_privs',

    # Additional keys that are either set by this script or are used to report
    # helpful errors to users.
    'mercury.arch',
    'mercury.id_map',
    'apollo.migrated',
    'mercury.rootfs.backend',
    'mercury.rootfs',
    'mercury.utsname',
    'mercury.aa_allow_incomplete',
    'mercury.autodev',
    'mercury.haltsignal',
    'mercury.rebootsignal',
    'mercury.stopsignal',
    'mercury.mount.entry',
    'mercury.cap.drop'
    # 'mercury.cap.keep',
    # 'mercury.seccomp',
    # 'mercury.se_context',
    ]


# Unix connection to APOLLO
class UnixHTTPConnection(http.client.HTTPConnection):
    def __init__(self, path):
        http.client.HTTPConnection.__init__(self, 'localhost')
        self.path = path

    def connect(self):
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.connect(self.path)
        self.sock = sock


# Fetch a config key as a list
def config_get(config, key, default=None):
    result = []
    for line in config:
        fields = line.split("=", 1)
        if fields[0].strip() == key:
            result.append(fields[-1].strip())

    if len(result) == 0:
        return default
    else:
        return result


def config_keys(config):
    keys = []
    for line in config:
        fields = line.split("=", 1)
        cur = fields[0].strip()
        if cur and not cur.startswith("#") and cur.startswith("mercury."):
            keys.append(cur)

    return keys


# Parse a MERCURY configuration file, called recursively for includes
def config_parse(path):
    config = []
    with open(path, "r") as fd:
        for line in fd:
            line = line.strip()
            key = line.split("=", 1)[0].strip()
            value = line.split("=", 1)[-1].strip()

            # Parse user-added includes
            if key == "mercury.include":
                # Ignore our own default configs
                if value.startswith("/usr/share/mercury/config/"):
                    continue

                if os.path.isfile(value):
                    config += config_parse(value)
                    continue
                elif os.path.isdir(value):
                    for entry in os.listdir(value):
                        if not entry.endswith(".conf"):
                            continue

                        config += config_parse(os.path.join(value, entry))
                    continue
                else:
                    print("Invalid include: %s", line)

            # Expand any fstab
            if key == "mercury.mount":
                if not os.path.exists(value):
                    print("Container fstab file doesn't exist, skipping...")
                    continue

                with open(value, "r") as fd:
                    for line in fd:
                        line = line.strip()
                        if (line and not line.startswith("#") and
                                line.startswith("mercury.")):
                            config.append("mercury.mount.entry = %s" % line)
                continue

            # Proces normal configuration keys
            if line and not line.strip().startswith("#"):
                config.append(line)

    return config


def container_exists(apollo_socket, container_name):
    apollo = UnixHTTPConnection(apollo_socket)
    apollo.request("GET", "/1.0/containers/%s" % container_name)
    if apollo.getresponse().status == 404:
        return False

    return True


def container_create(apollo_socket, args):
    # Define the container
    apollo = UnixHTTPConnection(apollo_socket)
    apollo.request("POST", "/1.0/containers", json.dumps(args))
    r = apollo.getresponse()

    # Decode the response
    resp = json.loads(r.read().decode())
    if resp["type"] == "error":
        raise Exception("Failed to define container: %s" % resp["error"])

    # Wait for result
    apollo = UnixHTTPConnection(apollo_socket)
    apollo.request("GET", "%s/wait" % resp["operation"])
    r = apollo.getresponse()

    # Decode the response
    resp = json.loads(r.read().decode())
    if resp["type"] == "error":
        raise Exception("Failed to define container: %s" % resp["error"])


# Convert a MERCURY container to a APOLLO one
def convert_container(apollo_socket, container_name, args):
    print("==> Processing container: %s" % container_name)

    # Load the container
    try:
        container = mercury.Container(container_name, args.mercurypath)
    except:
        print("Invalid container configuration, skipping...")
        return False

    # As some keys can't be queried over the API, parse the config ourselves
    print("Parsing MERCURY configuration")
    mercury_config = config_parse(container.config_file_name)
    found_keys = config_keys(mercury_config)

    # Generic check for any invalid MERCURY configuration keys.
    print("Checking for unsupported MERCURY configuration keys")
    diff = list(set(found_keys) - set(keys_to_check))
    for d in diff:
        if (not d.startswith('mercury.network.') and not
                d.startswith('mercury.cgroup.')):
            print("Found at least one unsupported config key %s: " % d)
            print("Not importing this container, skipping...")
            return False

    if args.debug:
        print("Container configuration:")
        print(" ", end="")
        print("\n ".join(mercury_config))
        print("")

    # Check for keys that have values differing from the APOLLO defaults.
    print("Checking whether container has already been migrated")
    if config_get(mercury_config, "apollo.migrated"):
        print("Container has already been migrated, skipping...")
        return False

    # Make sure we don't have a conflict
    print("Checking for existing containers")
    if container_exists(apollo_socket, container_name):
        print("Container already exists, skipping...")
        return False

    # Validating mercury.id_map: must be unset.
    print("Validating container mode")
    if config_get(mercury_config, "mercury.id_map"):
        print("Unprivileged containers aren't supported, skipping...")
        return False

    # Validate mercury.utsname
    print("Validating container name")
    value = config_get(mercury_config, "mercury.utsname")
    if value and value[0] != container_name:
        print("Container name doesn't match mercury.utsname, skipping...")
        return False

    # Validate mercury.aa_allow_incomplete: must be set to 0 or unset.
    print("Validating whether incomplete AppArmor support is enabled")
    value = config_get(mercury_config, "mercury.aa_allow_incomplete")
    if value and int(value[0]) != 0:
        print("Container allows incomplete AppArmor support, skipping...")
        return False

    # Validate mercury.autodev: must be set to 1 or unset.
    print("Validating whether mounting a minimal /dev is enabled")
    value = config_get(mercury_config, "mercury.autodev")
    if value and int(value[0]) != 1:
        print("Container doesn't mount a minimal /dev filesystem, skipping...")
        return False

    # Validate mercury.haltsignal: must be unset.
    print("Validating that no custom haltsignal is set")
    value = config_get(mercury_config, "mercury.haltsignal")
    if value:
        print("Container sets custom halt signal, skipping...")
        return False

    # Validate mercury.rebootsignal: must be unset.
    print("Validating that no custom rebootsignal is set")
    value = config_get(mercury_config, "mercury.rebootsignal")
    if value:
        print("Container sets custom reboot signal, skipping...")
        return False

    # Validate mercury.stopsignal: must be unset.
    print("Validating that no custom stopsignal is set")
    value = config_get(mercury_config, "mercury.stopsignal")
    if value:
        print("Container sets custom stop signal, skipping...")
        return False

    # Extract and valid rootfs key
    print("Validating container rootfs")
    value = config_get(mercury_config, "mercury.rootfs")
    if not value:
        print("Invalid container, missing mercury.rootfs key, skipping...")
        return False

    rootfs = value[0]

    if not os.path.exists(rootfs):
        print("Couldn't find the container rootfs '%s', skipping..." % rootfs)
        return False

    # Base config
    config = {}
    config['security.privileged'] = "true"
    devices = {}
    devices['eth0'] = {'type': "none"}

    # Convert network configuration
    print("Processing network configuration")
    try:
        count = len(container.get_config_item("mercury.network"))
    except:
        count = 0

    for i in range(count):
        device = {"type": "nic"}

        # Get the device type
        device["nictype"] = container.get_config_item("mercury.network")[i]

        # Get everything else
        dev = container.network[i]

        # Validate configuration
        if dev.ipv4 or dev.ipv4_gateway:
            print("IPv4 network configuration isn't supported, skipping...")
            return False

        if dev.ipv6 or dev.ipv6_gateway:
            print("IPv6 network configuration isn't supported, skipping...")
            return False

        if dev.script_up or dev.script_down:
            print("Network config scripts aren't supported, skipping...")
            return False

        if device["nictype"] == "none":
            print("\"none\" network mode isn't supported, skipping...")
            return False

        if device["nictype"] == "vlan":
            print("\"vlan\" network mode isn't supported, skipping...")
            return False

        # Convert the configuration
        if dev.hwaddr:
            device['hwaddr'] = dev.hwaddr

        if dev.link:
            device['parent'] = dev.link

        if dev.mtu:
            device['mtu'] = dev.mtu

        if dev.name:
            device['name'] = dev.name

        if dev.veth_pair:
            device['host_name'] = dev.veth_pair

        if device["nictype"] == "veth":
            if "parent" in device:
                device["nictype"] = "bridged"
            else:
                device["nictype"] = "p2p"

        if device["nictype"] == "phys":
            device["nictype"] = "physical"

        if device["nictype"] == "empty":
            continue

        devices['convert_net%d' % i] = device
        count += 1

    # Convert storage configuration
    value = config_get(mercury_config, "mercury.mount.entry", [])
    i = 0
    for entry in value:
        mount = entry.split(" ")
        if len(mount) < 4:
            print("Invalid mount configuration, skipping...")
            return False

        device = {'type': "disk"}

        # Deal with read-only mounts
        if "ro" in mount[3].split(","):
            device['readonly'] = "true"

        # Deal with optional mounts
        if "optional" in mount[3].split(","):
            device['optional'] = "true"
        elif not os.path.exists(mount[0]):
            print("Invalid mount configuration, source path doesn't exist.")
            return False

        # Set the source
        device['source'] = mount[0]

        # Figure out the target
        if mount[1][0] != "/":
            device['path'] = "/%s" % mount[1]
        else:
            device['path'] = mount[1].split(rootfs, 1)[-1]

        devices['convert_mount%d' % i] = device
        i += 1

    # Convert environment
    print("Processing environment configuration")
    value = config_get(mercury_config, "mercury.environment", [])
    for env in value:
        entry = env.split("=", 1)
        config['environment.%s' % entry[0].strip()] = entry[-1].strip()

    # Convert auto-start
    print("Processing container boot configuration")
    value = config_get(mercury_config, "mercury.start.auto")
    if value and int(value[0]) > 0:
        config['boot.autostart'] = "true"

    value = config_get(mercury_config, "mercury.start.delay")
    if value and int(value[0]) > 0:
        config['boot.autostart.delay'] = value[0]

    value = config_get(mercury_config, "mercury.start.order")
    if value and int(value[0]) > 0:
        config['boot.autostart.priority'] = value[0]

    # Convert apparmor
    print("Processing container apparmor configuration")
    value = config_get(mercury_config, "mercury.aa_profile")
    if value:
        if value[0] == "mercury-container-default-with-nesting":
            config['security.nesting'] = "true"
        elif value[0] != "mercury-container-default":
            config["raw.mercury"] = "mercury.aa_profile=%s" % value[0]

    # Convert seccomp
    print("Processing container seccomp configuration")
    value = config_get(mercury_config, "mercury.seccomp")
    if value:
        print("Custom seccomp profiles aren't supported, skipping...")
        return False

    # Convert SELinux
    print("Processing container SELinux configuration")
    value = config_get(mercury_config, "mercury.se_context")
    if value:
        print("Custom SELinux policies aren't supported, skipping...")
        return False

    # Convert capabilities
    print("Processing container capabilities configuration")
    value = config_get(mercury_config, "mercury.cap.drop")
    if value:
        print("Custom capabilities aren't supported, skipping...")
        return False

    value = config_get(mercury_config, "mercury.cap.keep")
    if value:
        print("Custom capabilities aren't supported, skipping...")
        return False

    # Setup the container creation request
    new = {'name': container_name,
           'source': {'type': 'none'},
           'config': config,
           'devices': devices,
           'profiles': ["default"]}

    # Set the container architecture if set in MERCURY
    print("Processing container architecture configuration")
    arches = {'i686': "i686",
              'x86_64': "x86_64",
              'armhf': "armv7l",
              'arm64': "aarch64",
              'powerpc': "ppc",
              'powerpc64': "ppc64",
              'ppc64el': "ppc64le",
              's390x': "s390x"}

    arch = None
    try:
        arch = config_get(mercury_config, "mercury.arch", None)

        if arch and arch[0] in arches:
            new['architecture'] = arches[arch[0]]
        else:
            print("Unknown architecture, assuming native.")
    except:
        print("Couldn't find container architecture, assuming native.")

    # Define the container in APOLLO
    if args.debug:
        print("APOLLO container config:")
        print(json.dumps(new, indent=True, sort_keys=True))

    if args.dry_run:
        return True

    if container.running:
        print("Only stopped containers can be migrated, skipping...")
        return False

    try:
        print("Creating the container")
        container_create(apollo_socket, new)
    except Exception as e:
        raise
        print("Failed to create the container: %s" % e)
        return False

    # Transfer the filesystem
    apollo_rootfs = os.path.join(args.apollopath, "containers",
                              container_name, "rootfs")

    if args.move_rootfs:
        if os.path.exists(apollo_rootfs):
            os.rmdir(apollo_rootfs)

        if subprocess.call(["mv", rootfs, apollo_rootfs]) != 0:
            print("Failed to move the container rootfs, skipping...")
            return False

        os.mkdir(rootfs)
    else:
        print("Copying container rootfs")
        if not os.path.exists(apollo_rootfs):
            os.mkdir(apollo_rootfs)

        if subprocess.call(["rsync", "-Aa", "--sparse",
                            "--acls", "--numeric-ids", "--hard-links",
                            "%s/" % rootfs, "%s/" % apollo_rootfs]) != 0:
            print("Failed to transfer the container rootfs, skipping...")
            return False

    # Delete the source
    if args.delete:
        print("Deleting source container")
        container.delete()

    # Mark the container as migrated
    with open(container.config_file_name, "a") as fd:
        fd.write("apollo.migrated=true\n")
    print("Container is ready to use")
    return True


# Argument parsing
parser = argparse.ArgumentParser()
parser.add_argument("--dry-run", action="store_true", default=False,
                    help="Dry run mode")
parser.add_argument("--debug", action="store_true", default=False,
                    help="Print debugging output")
parser.add_argument("--all", action="store_true", default=False,
                    help="Import all containers")
parser.add_argument("--delete", action="store_true", default=False,
                    help="Delete the source container")
parser.add_argument("--move-rootfs", action="store_true", default=False,
                    help="Move the container rootfs rather than copying it")
parser.add_argument("--mercurypath", type=str, default=False,
                    help="Alternate MERCURY path")
parser.add_argument("--apollopath", type=str, default="/var/lib/apollo",
                    help="Alternate APOLLO path")
parser.add_argument(dest='containers', metavar="CONTAINER", type=str,
                    help="Container to import", nargs="*")
args = parser.parse_args()

# Sanity checks
if not os.geteuid() == 0:
    parser.error("You must be root to run this tool")

if (not args.containers and not args.all) or (args.containers and args.all):
    parser.error("You must either pass container names or --all")

# Connect to APOLLO
apollo_socket = os.path.join(args.apollopath, "unix.socket")

if not os.path.exists(apollo_socket):
    print("APOLLO isn't running.")
    sys.exit(1)

# Run migration
results = {}
count = 0
for container_name in mercury.list_containers(config_path=args.mercurypath):
    if args.containers and container_name not in args.containers:
        continue

    if count > 0:
        print("")

    results[container_name] = convert_container(apollo_socket,
                                                container_name, args)
    count += 1

# Print summary
if not results:
    print("No container to migrate")
    sys.exit(0)

print("")
print("==> Migration summary")
for name, result in results.items():
    if result:
        print("%s: SUCCESS" % name)
    else:
        print("%s: FAILURE" % name)

if False in results.values():
    sys.exit(1)
